In [ ]:
import matplotlib.transforms as tr
import pandas as pd
import numpy as np ## use the matrix from here

In [ ]:
2#principal component analysis

x1 = []
x2 = []
x3 = []
#max elements  = 3

x = 3
i = 0
while i <=4:
    var1 = float(input("enter the number for row 1 "))
    var2 = float(input("enter the number for row 2 "))
    var3 = float(input("enter the number for row 3 "))
    11
    x1.append(var1)
    x2.append(var2)
    x3.append(var3)

    i = i +1

mean_x1,mean_x2,mean_x3 = np.mean(x1),np.mean(x2),np.mean(x3)

enter the number for row 1 6
enter the number for row 2 11
enter the number for row 3 14
enter the number for row 1 11
enter the number for row 2 6
enter the number for row 3 22
enter the number for row 1 5
enter the number for row 2 12
enter the number for row 3 23
enter the number for row 1 15
enter the number for row 2 8
enter the number for row 3 25
enter the number for row 1 9
enter the number for row 2 10
enter the number for row 3 16


In [ ]:
x1_x2 = []
x1_x3 = []
x2_x3 = []


for i in range(len(x1)):
    element1 = np.multiply(x1[i],x2[i])
    x1_x2.append(element1)
    element2 = np.multiply(x1[i],x3[i])
    x1_x3.append(element2)
    element3 = np.multiply(x2[i],x3[i])
    x2_x3.append(element3)

x1_x2

cov12 = np.mean(x1_x2)-mean_x1*mean_x2
cov13 = np.mean(x1_x3)-mean_x1*mean_x3
cov23 = np.mean(x2_x3)-mean_x2*mean_x3

var_x1 = np.var(x1)
var_x2 = np.var(x2)
var_x3 = np.var(x3)



In [ ]:
x__1 = [var_x1,cov12,cov13]
x__2 = [cov12,var_x2,cov23]
x__3 = [cov13,cov23,var_x3]

x_dataframe = pd.DataFrame([x__1,x__2,x__3])
x_dataframe

0     1     2
0  12.96 -6.08   8.0
1  -6.08  4.64  -3.6
2   8.00 -3.60  18.0

In [ ]:
df = x_dataframe.rename({0:"x1",1:"x2",2:"x3"}, axis='rows')
df

0     1     2
x1  12.96 -6.08   8.0
x2  -6.08  4.64  -3.6
x3   8.00 -3.60  18.0

In [ ]:
df = df.transpose()
df

x1    x2    x3
0  12.96 -6.08   8.0
1  -6.08  4.64  -3.6
2   8.00 -3.60  18.0

In [ ]:
from numpy.linalg import eig

w,v=eig(df)
print('E-value:', w)
print('E-vector', v)

E-value: [25.89364449  8.29966193  1.40669358]
E-vector [[-0.59944352  0.63212985  0.4909983 ]
 [ 0.29735588 -0.39365386  0.86983684]
 [-0.7431332  -0.66741928 -0.04800573]]


In [ ]:
v.T.dot([mean_x1,mean_x2,mean_x3])

In [ ]:
sdx1,sdx2,sdx3 = np.std(x1),np.std(x2),np.std(x3)
sdx1,sdx2,sdx3

(3.6, 2.1540659228538015, 4.242640687119285)

In [ ]:
x_1 = sdx1/(x1-mean_x1)
x_2 = sdx2/(x2-mean_x2)
x_3 = sdx3/(x3-mean_x3)

x_1,x_2,x_3


array = np.array([x_1,x_2,x_3])
array = array.transpose()

In [ ]:
covariance_matrix = (array.transpose())*(1/5)

In [ ]:
covariance_matrix = covariance_matrix.transpose()

In [ ]:
covariance_matrix

array([[-0.225     ,  0.26925824, -0.14142136],
       [ 0.4       , -0.12670976,  0.42426407],
       [-0.17142857,  0.16569738,  0.28284271],
       [ 0.12413793, -0.3077237 ,  0.16970563],
       [-3.6       ,  0.71802197, -0.21213203]])

In [ ]:
#covariance_matrix
cm =covariance_matrix
M1=np.dot(cm,v[0])
M2=np.dot(cm,v[1])
M3=np.dot(cm,v[2])

In [ ]:
M1,M2,M3

(array([ 0.23564332, -0.11156149,  0.34637929, -0.18560984,  2.50772331]),
 array([-0.29591312,  0.53786265,  0.1298243 ,  0.30566597, -1.53765354]),
 array([-0.00571414, -0.23305185,  0.00322657,  0.10498287,  2.20624136]))